run only 1 sanitized binary
srlabs/ziggy pull request #116
Opened 2024-12-18 15:31 UTC by Ollrogge

Currently, when fuzzing with multiple cores and ASAN enabled, we use the sanitized binary on all cores. This is unnecessary and degrades performance; instead, use the ASAN-compiled binary only on the first core.

Since we need two binaries for this, compile both a sanitized version and a not sanitized version if `ASAN` is enabled.

2024-12-18 16:15 UTC, louismerlin commented
Super cool! Do you have any idea what the speedup is?

2024-12-18 16:16 UTC, louismerlin requested changes
Can you please add some `eprintln` for "asan" before building the asan binary?

2024-12-19 10:27 UTC, Ollrogge commented
> Super cool! Do you have any idea what the speedup is?

No idea but I can / will measure :)

2024-12-20 13:59 UTC, Ollrogge commented
> Super cool! Do you have any idea what the speedup is?

Did some minimal benchmarking with the `url` example application. Running the fuzzer for 3 minutes I get: 

1 core: 
- ASan: cummulative speed 6.000 execs / sec  | best coverage: 2.71 %
- No ASan: cummulative speed: 54016 execs/sec | best coverage: 8.92%

10 cores:
- 10 ASan: cummulative speed 22.767 execs/sec | best coverage: 4.30 %
- 1 ASan + 9 No ASan: cummulative speed 137.464 execs/sec | best coverage: 19.40%

So the speedup is quite drastic :)

2024-12-24 13:25 UTC, R9295 commented
I don' think this is the right approach. IMO: we should rather run ASAN separately and then sync with the main fuzzer.

2025-03-12 09:13 UTC, merged