cleanup
srlabs/ziggy pull request #63
Opened 2023-09-28 15:52 UTC by vanhauser-thc

2023-09-28 15:52 UTC, vanhauser-thc commented on src/bin/cargo-ziggy/main.rs
>      perform_initial_minimization: bool,
can this be activated now? (or is it already?)

2023-09-29 12:40 UTC, louismerlin approved these changes

2023-09-29 12:41 UTC, louismerlin commented
Renamed `perform_initial_minimization` to `minimize`.

We can keep it off by default for now :) It's a simple `-m` away.

2023-10-04 08:45 UTC, louismerlin requested changes
`--no-honggfuzz -m` launches Honggfuzz minimization before running the fuzzers; I'll clean that up.

2023-10-04 09:53 UTC, louismerlin approved these changes

2023-10-04 09:56 UTC, merged